config/routes.rb
Rails.application.routes.draw do
  devise_for :receptionists
  devise_for :customers
  devise_for :admins
  devise_for :doctors

  resources :appointments
  resources :pets
  resources :doctors

  get '/doctors' => "doctors#index", as: :admin_root
  get '/appointments/new' => "appointments#new", as: :receptionist_root
  get '/pets/new' => "pets#new", as: :doctor_root
  get '/customer_appointments'=> "appointments#customer", as: :customer_root

  root 'pages#home'
  get '/exit' => "pages#exit", as: :exit_vet
end

app/views/pages/exit.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<ul class="hmenu">
  <% if !customer_signed_in? && !admin_signed_in? && !doctor_signed_in? %>
    <li>
      <ul>
        <li><%= link_to "Customer Sign In", new_customer_session_path%></li>
        <li><%= link_to "Admin Sign In", new_admin_session_path%></li>
        <li><%= link_to "Doctor Sign In", new_doctor_session_path%></li>
        <li><%= link_to "Receptionist Sign In", new_receptionist_session_path%></li>
      </ul>
    </li>
  <% end %>
</ul>

app/views/pages/home.html.erb
<h1>WELCOME TO THE VET!</h1>
<ul class="hmenu">
  <% if !customer_signed_in? && !admin_signed_in? && !doctor_signed_in? %>
    <li>
      <ul>
        <li><%= link_to "Customer Sign In", new_customer_session_path%></li>
        <li><%= link_to "Admin Sign In", new_admin_session_path%></li>
        <li><%= link_to "Doctor Sign In", new_doctor_session_path%></li>
        <li><%= link_to "Receptionist Sign In", new_receptionist_session_path%></li>
      </ul>
    </li>
  <% end %>
</ul>