config/routes.rb
Rails.application.routes.draw do
  devise_for :receptionists
  devise_for :customers
  devise_for :admins
  devise_for :doctors

  resources :appointments
  resources :pets
  resources :doctors

  get '/doctors' => "doctors#index", as: :admin_root
  get '/appointments/new' => "appointments#new", as: :receptionist_root
  get '/pets/new' => "pets#new", as: :doctor_root
  get '/customer_appointments'=> "appointments#customer", as: :customer_root

  root 'pages#home'
  get '/exit' => "pages#exit", as: :exit_vet
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :pet
  belongs_to :doctor
  has_one :customer, through: :pet

  validates :pet, presence: true
  validates :doctor, presence: true
  validates :reason, presence: true

  validate :date_cannot_be_in_the_past

  def date_cannot_be_in_the_past
    errors.add(:date_visit, "Can't be in the past") if
    !date_visit.blank? and date_visit < Date.today
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :require_receptionist, except: :customer

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def customer
    if customer_signed_in?
      @appointments = current_customer.appointments
      render :index
    else
      redirect_to root
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date_visit, :pet_id, :doctor_id, :reminder, :reason)
    end
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_visit %><br>
    <%= f.date_select :date_visit %>
  </div>
  <div class="field">
    <%= f.label :pet_id %><br>
    <%= f.collection_select :pet_id, Pet.order(:name),:id,:name, include_blank: false %>
  </div>
  <div class="field">
    <%= f.label :doctor_id %><br>
    <%= f.collection_select :doctor_id, Doctor.order(:name),:id,:name, include_blank: false %>
  </div>
  <div class="field">
    <%= f.label :reminder %><br>
    <%= f.check_box :reminder %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_area :reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Date visit</th>
      <th>Pet</th>
      <th>Customer</th>
      <th>Doctor</th>
      <th>Reminder</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date_visit %></td>
        <td><%= appointment.pet.name %></td>
        <td><%= appointment.pet.customer.email %></td>
        <td><%= appointment.doctor.name %></td>
        <td><%= appointment.reminder %></td>
        <td><%= appointment.reason %></td>
        <td><%= link_to 'Show', appointment unless customer_signed_in? %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment)  unless customer_signed_in? %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' }  unless customer_signed_in? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path unless customer_signed_in? %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date visit:</strong>
  <%= @appointment.date_visit %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @appointment.pet.name %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @appointment.pet.customer.email %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @appointment.doctor.name %>
</p>

<p>
  <strong>Reminder:</strong>
  <%= @appointment.reminder %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @appointment.reason %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>